In [1]:
import pandas as pd
import numpy as np
import folium

df = pd.read_csv('milfoil_tableB_all_years_cleaned.csv')

df

       id  sample_point   latitude  longitude milfoil_presence  year
0       0             1  42.977652 -75.887120                M  2008
1       1             2  42.977520 -75.887213                S  2008
2       2             3  42.977661 -75.887699                M  2008
3       3             4  42.977674 -75.888337                M  2008
4       4             5  42.977542 -75.889355                M  2008
...   ...           ...        ...        ...              ...   ...
4859  299           300  42.960420 -75.871387                T  2023
4860  300           301  42.961219 -75.871882                T  2023
4861  301           302  42.961837 -75.872214                T  2023
4862  302           303  42.948490 -75.866480                S  2023
4863  303           304  42.948360 -75.866510                S  2023

[4864 rows x 6 columns]

In [2]:
df['corrected_longitude'] = np.where(df['longitude'] > 0, df['longitude']*-1, df['longitude'])
df

,id,sample_point,latitude,longitude,milfoil_presence,year,corrected_longitude
0,0,1,42.977652,-75.887120,M,2008,-75.887120
1,1,2,42.977520,-75.887213,S,2008,-75.887213
2,2,3,42.977661,-75.887699,M,2008,-75.887699
3,3,4,42.977674,-75.888337,M,2008,-75.888337
4,4,5,42.977542,-75.889355,M,2008,-75.889355
...,...,...,...,...,...,...,...
4859,299,300,42.960420,-75.871387,T,2023,-75.871387
4860,300,301,42.961219,-75.871882,T,2023,-75.871882
4861,301,302,42.961837,-75.872214,T,2023,-75.872214
4862,302,303,42.948490,-75.866480,S,2023,-75.866480
4863,303,304,42.948360,-75.866510,S,2023,-75.866510

In [3]:
lake_map_2008 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)
lake_map_2008

In [4]:
df['milfoil_presence'].unique()

array(['M', 'S', 'D', nan, 'T', ' ', 'T '], dtype=object)

In [5]:
df['milfoil_presence'] = df['milfoil_presence'].fillna('N')
df

,id,sample_point,latitude,longitude,milfoil_presence,year,corrected_longitude
0,0,1,42.977652,-75.887120,M,2008,-75.887120
1,1,2,42.977520,-75.887213,S,2008,-75.887213
2,2,3,42.977661,-75.887699,M,2008,-75.887699
3,3,4,42.977674,-75.888337,M,2008,-75.888337
4,4,5,42.977542,-75.889355,M,2008,-75.889355
...,...,...,...,...,...,...,...
4859,299,300,42.960420,-75.871387,T,2023,-75.871387
4860,300,301,42.961219,-75.871882,T,2023,-75.871882
4861,301,302,42.961837,-75.872214,T,2023,-75.872214
4862,302,303,42.948490,-75.866480,S,2023,-75.866480
4863,303,304,42.948360,-75.866510,S,2023,-75.866510

In [6]:
df2008 = df.loc[df.year == 2008]
df2008

,id,sample_point,latitude,longitude,milfoil_presence,year,corrected_longitude
0,0,1,42.977652,-75.887120,M,2008,-75.887120
1,1,2,42.977520,-75.887213,S,2008,-75.887213
2,2,3,42.977661,-75.887699,M,2008,-75.887699
3,3,4,42.977674,-75.888337,M,2008,-75.888337
4,4,5,42.977542,-75.889355,M,2008,-75.889355
...,...,...,...,...,...,...,...
297,297,298,42.959125,-75.870077,M,2008,-75.870077
298,298,299,42.959650,-75.870627,D,2008,-75.870627
299,299,300,42.960420,-75.871387,D,2008,-75.871387
300,300,301,42.961219,-75.871882,D,2008,-75.871882
301,301,302,42.961837,-75.872214,D,2008,-75.872214

In [7]:
# none, trace, sparse, moderate, dense
milfoil_abundance = ['N', 'T', 'S', 'M', 'D'] # use index for number value

In [26]:
points_2008 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2008.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2008.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None, #'green', 
          fill_color='#008000', 
          fill_opacity=0.5,
      ).add_to(lake_map_2008)
print(len(points_2008))
lake_map_2008

281

In [9]:
df2009 = df.loc[df.year == 2009]
lake_map_2009 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

In [10]:
points_2009 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2009.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2009.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2009)
print(len(points_2009))
lake_map_2009

124

In [11]:
df2010 = df.loc[df.year == 2010]
lake_map_2010 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

points_2010 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2010.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2010.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2010)
print(len(points_2010))
lake_map_2010

88

In [12]:
df2011 = df.loc[df.year == 2011]
lake_map_2011 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

points_2011 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2011.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2011.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2011)
print(len(points_2011))
lake_map_2011

223

In [13]:
df2012 = df.loc[df.year == 2012]
lake_map_2012 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

points_2012 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2012.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2012.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2012)
print(len(points_2012))        
lake_map_2012

124

In [14]:
df2013 = df.loc[df.year == 2013]
lake_map_2013 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

points_2013 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2013.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2013.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2013)
print(len(points_2013))
lake_map_2013

258

In [15]:
df2014 = df.loc[df.year == 2014]
lake_map_2014 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

points_2014 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2014.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2014.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2014)
print(len(points_2014))
lake_map_2014

206

In [16]:
df2015 = df.loc[df.year == 2015]
lake_map_2015 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

points_2015 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2015.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2015.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2015)
print(len(points_2015))
lake_map_2015

286

In [17]:
df2016 = df.loc[df.year == 2016]
lake_map_2016 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

points_2016 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2016.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2016.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2016)
print(len(points_2016))
lake_map_2016

290

In [18]:
df2017 = df.loc[df.year == 2017]
lake_map_2017 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

points_2017 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2017.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2017.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2017)
print(len(points_2017))
lake_map_2017

166

In [19]:
df2018 = df.loc[df.year == 2018]
lake_map_2018 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

points_2018 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2018.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2018.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2018)
print(len(points_2018))
lake_map_2018

284

In [20]:
df2019 = df.loc[df.year == 2019]
lake_map_2019 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

points_2019 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2019.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2019.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2019)
print(len(points_2019))
lake_map_2019

117

In [21]:
df2020 = df.loc[df.year == 2020]
lake_map_2020 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

points_2020 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2020.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2020.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2020)
print(len(points_2020))
lake_map_2020

238

In [22]:
df2021 = df.loc[df.year == 2021]
lake_map_2021 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

points_2021 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2021.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2021.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2021)
print(len(points_2021))
lake_map_2021

25

In [23]:
df2022 = df.loc[df.year == 2022]
lake_map_2022 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

points_2022 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2022.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2022.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2022)
print(len(points_2022))
lake_map_2022

114

In [24]:
df2023 = df.loc[df.year == 2023]
lake_map_2023 = folium.Map(location=[42.950253, -75.870825], zoom_start=13)

points_2023 = []

for ma_index, value in enumerate(milfoil_abundance):
  for df_index, row in df2023.iterrows():
    if row['milfoil_presence'] == value:
      if ma_index > 0:
        points_2023.append(df_index)
        folium.features.CircleMarker(
          [row['latitude'], row['corrected_longitude']],
          radius=ma_index,
          color=None,
          fill_color='#008000', 
          fill_opacity=0.5,
        ).add_to(lake_map_2023)
print(len(points_2023))
lake_map_2023

229